import pygame
import os
import copy
import json
pygame.font.init()

#RGB
RED = (255, 0, 0)
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
BLUE = (0, 0, 255)
GREY = (128, 128, 128)
GREY_7 = (32, 32, 32)
GREY_6 = (64, 64, 64)
GREY_5 = (96, 96, 96)
GREY_3 = (160, 160, 160)
GREY_2 = (192, 192, 192)
GREY_1 = (224, 224, 224)
GREEN_2 = (0, 154, 0)
GREEN_1 = (0, 204, 0)

# Basic Parameters
DEFAULT_FONT = 'comicsans'
WIDTH, HEIGHT = 1300, 800
ROWS = 15
COLS = ROWS
BOARD_SIDE_PADDING = 20
BOARD_TOP_PADDING = 80
BOARD_BOTTOM_PADDING = 10
BOARD_LENGTH = HEIGHT - BOARD_TOP_PADDING - BOARD_BOTTOM_PADDING
SQUARE_SIZE = BOARD_LENGTH // ROWS
BOARD_START = (BOARD_SIDE_PADDING, BOARD_TOP_PADDING)

#Console
CONSOLE_LEFT_PADDING = 20
CONSOLE_BOTTOM_PADDING = BOARD_BOTTOM_PADDING
CONSOLE_RIGHT_PADDING = 40
CONSOLE_HEIGHT = 400
CONSOLE_LENGTH = WIDTH - CONSOLE_LEFT_PADDING - CONSOLE_RIGHT_PADDING - BOARD_LENGTH - BOARD_SIDE_PADDING
CONSOLE_TEXT_SIZE = 25
CONSOLE_TEXT_FONT = pygame.font.SysFont(DEFAULT_FONT, CONSOLE_TEXT_SIZE)

#Panel
PANEL_LEFT_PADDING = 20
PANEL_RIGHT_PADDING = 40
PANEL_TOP_PADDING = BOARD_TOP_PADDING
PANEL_LENGTH = WIDTH - PANEL_LEFT_PADDING - PANEL_RIGHT_PADDING - BOARD_LENGTH - BOARD_SIDE_PADDING
PANEL_HEIGHT = 200
PANEL_INT_PADD = 10
PANEL_FONT_SIZE = 30
PANEL_FONT = pygame.font.SysFont(DEFAULT_FONT, PANEL_FONT_SIZE)

#BUTTON
BUTTON_PADDING = 10
BUTTON_INT_PADDING = 5
POTENTIAL_B_WIDTH = 80
POTENTIAL_B_HEIGHT = 40
RESET_B_WIDTH = 70
RESET_B_HEIGHT = 40

SETTINGS_BUTTON_PADDING = (BOARD_TOP_PADDING + SQUARE_SIZE//2) // 4
SETTINGS_BUTTON_HEIGHT = (BOARD_TOP_PADDING + SQUARE_SIZE//2) // 10 * 5
SETTINGS_BUTTON_WIDTH = 100

SETTINGS_PADDING = 50
SETTINGS_WIDTH = WIDTH - SETTINGS_PADDING * 2
SETTINGS_HEIGHT = HEIGHT - SETTINGS_PADDING * 2

UNREDO_BUTTON_WIDTH = 80
UNREDO_BUTTON_HEIGHT = 40

SAVE_RESTART_BUTTON_WIDTH = 150
SAVE_RESTART_BUTTON_HEIGHT = 40

SETT_TIME_DISP_WIDTH = 180
SETT_TIME_DISP_HEIGHT = 50

BUTTON_HEIGHT_XL = 80
BUTTON_HEIGHT_L = 60
BUTTON_HEIGHT_M = 40
BUTTON_HEIGHT_S = 30

DISPLAY_HEIGHT_XL = 100
DISPLAY_HEIGHT_L = 80
DISPLAY_HEIGHT_M = 60
DISPLAY_HEIGHT_S = 40
DISPLAY_HEIGHT_XS = 30

#Settings

SETTINGS_TITLE_FONT_SIZE = 40
SETTINGS_PADDING = 20
SETTINGS_INT_PADDING = 10

#Timer
TIMER_PADDING = BOARD_TOP_PADDING // 7
TIMER_WIDTH = BOARD_LENGTH // 3
TIMER_HEIGHT = BOARD_TOP_PADDING - TIMER_PADDING * 2
TIMER_X = BOARD_SIDE_PADDING + BOARD_LENGTH // 2 - TIMER_WIDTH // 2
TIMER_Y = TIMER_PADDING
TIMER_BORDER_COLOR = BLACK
TIMER_BORDER_THICKNESS = TIMER_HEIGHT // 10
TIMER_COLOR = GREY

with open(os.path.join('omokFiles', 'settings.json')) as json_file:
    SETTINGS = json.load(json_file)

NEW_SETTINGS = copy.deepcopy(SETTINGS)

DRAW_B_POT, DRAW_W_POT, DRAW_N_POT = 'dbp', 'dwp', 'dnp'

LINE_THICKNESS = 2
STONE_PADDING = 2
ILLEGAL_SQUARE_PADDING = 2
ILLEGAL_SQUARE = pygame.Surface((SQUARE_SIZE - ILLEGAL_SQUARE_PADDING*2, SQUARE_SIZE - ILLEGAL_SQUARE_PADDING*2))
ILLEGAL_SQUARE.set_alpha(64)
ILLEGAL_SQUARE.fill(RED)

DELTA = {'v': (1,0), 'VH': (1,1), 'h': (0,1), 'vh': (-1, 1)}
DIRTOIND = {'v': 0, 'VH': 1, 'h': 2, 'vh': 3}

WOOD_BACKGROUND = pygame.transform.scale(pygame.image.load(os.path.join('Assets', 'wood_background.jpg')), (WIDTH, HEIGHT))

# with open(os.path.join('omokFiles', 'black_potential.json')) as json_file1:
#     BLACK_POTENTIAL = json.load(json_file1)
BLACK_POTENTIAL = {}

# with open(os.path.join('omokFiles', 'white_potential.json')) as json_file2:
#     WHITE_POTENTIAL = json.load(json_file2)
WHITE_POTENTIAL = {}

POT_FONT_SIZE = SQUARE_SIZE // 3
POT_FONT_DIS = POT_FONT_SIZE // 2 + 1
POTENTIAL_FONT = pygame.font.SysFont(DEFAULT_FONT, POT_FONT_SIZE)
POT_FONT_CORR = 3
FIRST = True

B_POT_TO_COLOR = {'na': GREY_2, '00': GREY_2, 'c1': GREY_3, 'o1': GREY_3, 'c2': GREY_3, 'o2': GREY_5, 'c3': GREY_5, 'o3': GREY_6, 'c4': GREY_7, 'o4': GREY_7, 'x4': GREY_7, '05': BLACK}
ONLY_WHITE_COLOR = {'06': BLACK, '07': BLACK, '08': BLACK, '09': BLACK, '10': BLACK, '11': BLACK, '12': BLACK, '13': BLACK, '14': BLACK, '15': BLACK}
W_POT_TO_COLOR = {**B_POT_TO_COLOR, **ONLY_WHITE_COLOR}
B_POT_TO_COLOR = W_POT_TO_COLOR

#Events
RESET_EVENT = pygame.USEREVENT + 1
SETTINGS_EVENT = pygame.USEREVENT + 2