import pygame
import os

WIDTH, HEIGHT = 600, 780
ROWS = 15
COLS = ROWS
BOARD_SIDE_PADDING = 20
SQUARE_SIZE = (WIDTH - BOARD_SIDE_PADDING * 2) // ROWS
BOARD_BOTTOM_PADDING = 40
BOARD_LENGTH = WIDTH - BOARD_SIDE_PADDING * 2
BOARD_START = (BOARD_SIDE_PADDING, HEIGHT - (BOARD_LENGTH + BOARD_BOTTOM_PADDING))

LINE_THICKNESS = 2
STONE_PADDING = 2

WOOD_BACKGROUND = pygame.transform.scale(pygame.image.load(os.path.join('Assets', 'wood_background.jpg')), (WIDTH, HEIGHT))

#RGB
RED = (255, 0, 0)
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
BLUE = (0, 0, 255)
GREY = (128, 128, 128)