import pygame
import os
import json
pygame.font.init()


WIDTH, HEIGHT = 1200, 800
ROWS = 15
COLS = ROWS
BOARD_SIDE_PADDING = 20
BOARD_TOP_PADDING = 40
BOARD_BOTTOM_PADDING = BOARD_TOP_PADDING
BOARD_LENGTH = HEIGHT - BOARD_TOP_PADDING * 2
SQUARE_SIZE = BOARD_LENGTH // ROWS
BOARD_START = (BOARD_SIDE_PADDING, BOARD_TOP_PADDING)

CONSOLE_LEFT_PADDING = 20
CONSOLE_BOTTOM_PADDING = BOARD_BOTTOM_PADDING
CONSOLE_RIGHT_PADDING = 40
CONSOLE_HEIGHT = 400
CONSOLE_LENGTH = WIDTH - CONSOLE_LEFT_PADDING - CONSOLE_RIGHT_PADDING - BOARD_LENGTH - BOARD_SIDE_PADDING

PANEL_LEFT_PADDING = 20
PANEL_RIGHT_PADDING = 40
PANEL_TOP_PADDING = BOARD_TOP_PADDING
PANEL_LENGTH = WIDTH - PANEL_LEFT_PADDING - PANEL_RIGHT_PADDING - BOARD_LENGTH - BOARD_SIDE_PADDING
PANEL_HEIGHT = 200
PANEL_INT_PADD = 10
PANEL_FONT_SIZE = 30
PANEL_FONT = pygame.font.SysFont('comicsans', PANEL_FONT_SIZE)

BUTTON_PADDING = 10
BUTTON_INT_PADDING = 5
POTENTIAL_B_WIDTH = 80
POTENTIAL_B_HEIGHT = 40
RESET_B_WIDTH = 70
RESET_B_HEIGHT = 40

CONSOLE_TEXT_SIZE = 25
CONSOLE_TEXT_FONT = pygame.font.SysFont('comicsans', CONSOLE_TEXT_SIZE)

DRAW_B_POT, DRAW_W_POT, DRAW_N_POT = 'dbp', 'dwp', 'dnp'

LINE_THICKNESS = 2
STONE_PADDING = 2
DELTA = {'v': (1,0), 'VH': (1,1), 'h': (0,1), 'vh': (-1, 1)}
DIRTOIND = {'v': 0, 'VH': 1, 'h': 2, 'vh': 3}

WOOD_BACKGROUND = pygame.transform.scale(pygame.image.load(os.path.join('Assets', 'wood_background.jpg')), (WIDTH, HEIGHT))

with open(os.path.join('omokFiles', 'black_potential.json')) as json_file1:
    BLACK_POTENTIAL = json.load(json_file1)

with open(os.path.join('omokFiles', 'white_potential.json')) as json_file2:
    WHITE_POTENTIAL = json.load(json_file2)


POT_FONT_SIZE = SQUARE_SIZE // 3
POT_FONT_DIS = POT_FONT_SIZE // 2 + 1
POTENTIAL_FONT = pygame.font.SysFont('comicsans', POT_FONT_SIZE)
POT_FONT_CORR = 3
FIRST = True

#RGB
RED = (255, 0, 0)
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
BLUE = (0, 0, 255)
GREY = (128, 128, 128)
GREY_7 = (32, 32, 32)
GREY_6 = (64, 64, 64)
GREY_5 = (96, 96, 96)
GREY_3 = (160, 160, 160)
GREY_2 = (192, 192, 192)
GREY_1 = (224, 224, 224)

B_POT_TO_COLOR = {'na': GREY_2, '00': GREY_2, 'c1': GREY_3, 'o1': GREY_3, 'c2': GREY_3, 'o2': GREY_5, 'c3': GREY_5, 'o3': GREY_6, 'c4': GREY_7, 'o4': GREY_7, '05': BLACK}
ONLY_WHITE_COLOR = {'06': BLACK, '07': BLACK, '08': BLACK, '09': BLACK, '10': BLACK, '11': BLACK, '12': BLACK, '13': BLACK, '14': BLACK, '15': BLACK}
W_POT_TO_COLOR = {**B_POT_TO_COLOR, **ONLY_WHITE_COLOR}

#Events
RESET_EVENT = pygame.USEREVENT + 1